services:
  middleware:
    image: romannjoroge/emerging-technologies:latest
    ports:
      - 5000:3000
    environment:
      PORT: 3000
  frontend:
    image: mbeka02/emerging-technologies:latest
    ports:
      - 1000:80
    depends_on:
      - backend # Ensures backend starts first
    environment:
      - VITE_API_URL=http://backend:5000 # Assuming backend runs on port 5000
  backend:
    image: romannjoroge/emerging-technologies-backend:tagname:latest
    environment:
      - BASEHOST=http://middleware:3000
      - PORT=5000
    ports:
      - 5001:5000
    depends_on:
      - middleware
