services:
  middleware:
    image: romannjoroge/emerging-technologies:latest 
    ports:
      - 3000:5000
    environment:
      PORT: 3000
  frontend:
    image: mbeka02/emerging-technologies
    ports:
      - 1000:80
  backend:
    image: patrickojiambo/emerging-backend:tag
