services:
  middleware:
    image: romannjoroge/emerging-technologies:latest
    ports:
      - 3000:5000
    environment:
      PORT: 3000
  frontend:
    image: mbeka02/emerging-technologies:latest
    ports:
      - 1000:80
    depends_on:
      - backend # Ensures backend starts first
    environment:
      - BACKEND_API_URL=http://backend:5000 # Assuming backend runs on port 5000
  backend:
    image: patrickojiambo/emerging-backend:tag
    depends_on:
      - middleware
